import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// 先跑构建期代码生成，再交给 esbuild 打包。
// 两步都是"源 → 生成物"的纯代码生成，产物不入库（见 .gitignore 的 src/game/generated/）：
//   build-game.mjs  把上游脚本拼成隔离作用域的 src/game/generated/adr.runtime.js
//   scope-css.mjs   把上游样式作用域化，输出插件根目录的 styles.css
// 注意：本插件不复制任何二进制资源 —— 上游的 audio/ 与 img/ 都未随包分发。
console.log("[build] 生成游戏运行时…");
await import("./scripts/build-game.mjs");
console.log("[build] 生成作用域化样式…");
await import("./scripts/scope-css.mjs");

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  await context.rebuild();

  // 发布产物：Obsidian 只认 main.js / styles.css / manifest.json 三个文件
  const outputDir = "output";
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }
  for (const file of ["main.js", "styles.css", "manifest.json"]) {
    if (fs.existsSync(file)) {
      fs.copyFileSync(file, path.join(outputDir, file));
      console.log(`Copied ${file} to ${outputDir}/`);
    }
  }

  await context.dispose();
  process.exit(0);
} else {
  await context.watch();
}
