import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";
import { builtinModules } from "module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// 构建期只生成游戏运行时，再交给 esbuild 打包。
// 生成物不入库（见 .gitignore 的 src/game/generated/）：
//   build-game.mjs  把上游脚本拼成隔离作用域的 src/game/generated/adr.runtime.js
// 样式不走构建期生成：根目录 styles.css 是唯一的手工维护样式表
// （上游样式已一次性作用域化并固化在其中，见该文件顶部的说明）。
// 注意：本插件不复制任何二进制资源 —— 上游的 audio/ 与 img/ 都未随包分发。
console.log("[build] 生成游戏运行时…");
await import("./scripts/build-game.mjs");

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  await context.rebuild();

  // 发布产物：Obsidian 只认 main.js / styles.css / manifest.json 三个文件
  const outputDir = "output";
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }
  for (const file of ["main.js", "styles.css", "manifest.json"]) {
    if (fs.existsSync(file)) {
      fs.copyFileSync(file, path.join(outputDir, file));
      console.log(`Copied ${file} to ${outputDir}/`);
    }
  }

  await context.dispose();
  process.exit(0);
} else {
  await context.watch();
}
